### ISSUE TITLE
Duplicate struct definition

### ISSUE THREAD

**Issue by chrisseaton** [david942j/crabstone#9]
Is this code as intended?

https://github.com/david942j/crabstone/blob/a7e3b6f401d916787d56761955607ddb04b895ef/lib/crabstone/arch/4/x86.rb#L55-L89

FFI is warning about it. It also doesn't make immediate sense to me.

```
[DEPRECATION] Struct layout is already defined for class Crabstone::X86::Instruction. Redefinition as in /Users/chrisseaton/.gem/ruby/2.5.8/gems/crabstone-4.0.2/lib/crabstone/arch/4/x86.rb:68:in `<class:Instruction>' will be disallowed in ffi-2.0.
```

**Comment by david942j** [comment]
Interesting.. must be a bug.

Thanks for the report!

**Comment by david942j** [comment]
The new 4.0.3 release of Crabstone contains the fix, thanks for pointing out this again!

**Comment by chrisseaton** [comment]
Thanks very much for responding so quickly and doing the release straight away. We're using this gem at Shopify for some compiler research.
